### ISSUE TITLE
Triggers like 'when washing machine is done' missing

### ISSUE THREAD

**Issue by stefanwitkamp** [athombv/com.home-connect#1]
The BSH HC plaform offers control, but also monitoring and notifications of devices. At the moment, Homey does not support these notifications - there are no Flow Trigger cards. It would be great if this was added, as to let your light bulbs flash when the washing machine is done and you're at home, for instance.

**Comment by irritanterik** [comment]
This looks lika an 'When washing machine is done' trigger to me. (beta app version)
![image](https://user-images.githubusercontent.com/15232724/41160091-dfb64780-6b2e-11e8-8b4c-710352f88cb9.png)

**Comment by stefanwitkamp** [comment]
Is it stable enough at the Home Connect side of things? :)

**Comment by irritanterik** [comment]
@stefanwitkamp To be honest I never experienced a succesfull trigger... I'm not sure its a bug on the Homey-app or in the Bosch api. Notifications on the native bosch app are working correct though...

**Comment by WeeJeWel** [comment]
Unfortunately it's their API that's not working. Push notifications to a smartphone use a different service.

I'll ask them (again) to fix it.

**Comment by WeeJeWel** [comment]
I've tested it again and it seems to work. If not, please reply.

**Comment by sevenam** [comment]
This works for about a day or so after restarting the app.
