### ISSUE TITLE
Please add the dishing machine HomeConnect button trigger

### ISSUE THREAD

**Issue by Bloke63** [athombv/com.home-connect#2]
Hi developer, 

Thank you for bringing these features to Homey. All available implemented options for the dishwasher are working great. However one key feature/trigger is missing.

On an IQ700 dishwasher there is a HomeConnect physical touch button you have to push/active before a washing program can be started remotely. 

1. This HomeConnect button only is available when the machine is powered on.
2. When the door is opened (while the button was active, before a program is remotely started) this button will automatically turn itself off 

The status of this HomeConnect remote start button is important to be able to automate a start sequence.
If this trigger is not activated the machine will not start remotely at all.

Also I cannot use the HomeConnect options as an secondary trigger.

A Flow I would like to make:

- IF...
1. HomeConnect trigger on machine is active (program can be started remotely) 
...AND...
2. Solar energy yield is sufficient from the solar panels
...THEN
3. Start a predefined washing program

Available HomeConnect Dishwasser triggers are:
**The only _when ..._ option that are available**:
The door has been opened = De deur is opengemaakt
The door has been closed = De deur is dichtgemaaht
A program has finished =Een programma is klaar

**There are no _...and..._ and _or_ options available**

**_...Then_ options are:**
Stop the active program
Start Program

Currently running v1.5.0 beta

**Comment by Bloke63** [comment]
Found some info on this issue:
https://developer.home-connect.com/?q=getting_started/overview

“Remote Control States

duplicated linked frameworks

A Home Connect enabled appliance can have different possible states, which reflect how they can be remote controled.”

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2597
